/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.NationType;
import Model.SavedData;
import java.awt.Container;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author taha
 */
public class GameMode extends javax.swing.JPanel {

    /**
     * Creates new form GameMode
     */
    
    JFrame frame;
    Container panel;
    public GameMode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void copyFrameMain(JFrame frame){
        this.frame = frame;
    }
    
    public void copyContentPaneMain(Container panel){
        this.panel = panel;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campaignButton = new javax.swing.JButton();
        skirmishButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        campaignButton.setText("Campaign");
        campaignButton.setMaximumSize(new java.awt.Dimension(200, 150));
        campaignButton.setMinimumSize(new java.awt.Dimension(200, 150));
        campaignButton.setPreferredSize(new java.awt.Dimension(200, 150));
        campaignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campaignButtonActionPerformed(evt);
            }
        });

        skirmishButton.setText("Skirmish");
        skirmishButton.setMaximumSize(new java.awt.Dimension(200, 150));
        skirmishButton.setMinimumSize(new java.awt.Dimension(200, 150));
        skirmishButton.setPreferredSize(new java.awt.Dimension(200, 150));
        skirmishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skirmishButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(campaignButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skirmishButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campaignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skirmishButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(256, 256, 256))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campaignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campaignButtonActionPerformed
        boolean enter = true;
        File file = new File("Save.cw");
        if(file.exists()){
            final String message = 
                "There is a saved game.\n"
                + "You will lose your previous game.\n"
                +"Do you want to continue?";
            int reply = JOptionPane.showConfirmDialog(this, message,"Warning", JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if(reply==JOptionPane.YES_OPTION)
                System.out.println("Okay");
            if(reply==JOptionPane.NO_OPTION)
                enter = false;
                
        }
        
        if(enter)
        {
            try{
                FileOutputStream fos = new FileOutputStream("Save.cw");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                Object save = new SavedData(1);
                oos.writeObject(save);
                oos.close();
            }
            catch (IOException ex) {
                Logger.getLogger(GraphicManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        GameView game = new GameView(1, "campaign", 1, NationType.Doth);
        game.copyFrameMain(frame);
        game.copyContentPaneMain(panel);
        game.Start();
        frame.setContentPane(game);
    }//GEN-LAST:event_campaignButtonActionPerformed

    private void skirmishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skirmishButtonActionPerformed
        GameOptions go = new GameOptions();
        go.copyFrameMain(frame);
        go.copyContentPaneMain(panel);
        frame.setContentPane(go);
    }//GEN-LAST:event_skirmishButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        frame.setContentPane(panel);
        frame.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton campaignButton;
    private javax.swing.JButton skirmishButton;
    // End of variables declaration//GEN-END:variables
}
