/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MapLocationLabel;
import Controller.NationType;
import Model.SavedData;
import java.awt.Container;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author emre
 */
public class LoadGameWindow extends javax.swing.JPanel {

    /**
     * Creates new form LoadGameWindow
     */
    
    JFrame frame;
    Container panel;
    int level = 0;
    ArrayList<MapLocationLabel> locationList;
    public LoadGameWindow() {
        initComponents();
        FileInputStream fis;
        SavedData result = null;
        try {
            fis = new FileInputStream("Save.cw");
            ObjectInputStream ois = new ObjectInputStream(fis);
            result = (SavedData) ois.readObject();
            ois.close();
            level = result.getCurrentLevel();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoadGameWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoadGameWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoadGameWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i = 0; i<locationList.size(); i++){
            if(locationList.get(i).getLevelNumber()<=result.getCurrentLevel()){
                locationList.get(i).setPlayable(true);
            }
            else {
                break;
            }
        }
        
    }
    
    public void copyFrameMain(JFrame frame){
        this.frame = frame;
    }
    
    public void copyContentPaneMain(Container panel){
        this.panel = panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        mapLocationLabel1 = new Controller.MapLocationLabel(1);
        mapLocationLabel2 = new Controller.MapLocationLabel(2);
        mapLocationLabel3 = new Controller.MapLocationLabel(3);
        mapLocationLabel4 = new Controller.MapLocationLabel(4);
        mapLocationLabel5 = new Controller.MapLocationLabel(5);

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backButtonMousePressed(evt);
            }
        });

        mapLocationLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mapLocationLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mapLocationLabel1.setMaximumSize(new java.awt.Dimension(64, 84));
        mapLocationLabel1.setMinimumSize(new java.awt.Dimension(64, 84));
        mapLocationLabel1.setPreferredSize(new java.awt.Dimension(64, 84));
        mapLocationLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapLocationLabel1MouseClicked(evt);
            }
        });

        mapLocationLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mapLocationLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mapLocationLabel2.setMaximumSize(new java.awt.Dimension(64, 84));
        mapLocationLabel2.setMinimumSize(new java.awt.Dimension(64, 84));
        mapLocationLabel2.setPreferredSize(new java.awt.Dimension(64, 84));
        mapLocationLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapLocationLabel2MouseClicked(evt);
            }
        });

        mapLocationLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mapLocationLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mapLocationLabel3.setMaximumSize(new java.awt.Dimension(64, 84));
        mapLocationLabel3.setMinimumSize(new java.awt.Dimension(64, 84));
        mapLocationLabel3.setPreferredSize(new java.awt.Dimension(64, 84));
        mapLocationLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapLocationLabel3MouseClicked(evt);
            }
        });

        mapLocationLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mapLocationLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mapLocationLabel4.setMaximumSize(new java.awt.Dimension(64, 84));
        mapLocationLabel4.setMinimumSize(new java.awt.Dimension(64, 84));
        mapLocationLabel4.setPreferredSize(new java.awt.Dimension(64, 84));
        mapLocationLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapLocationLabel4MouseClicked(evt);
            }
        });

        mapLocationLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mapLocationLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mapLocationLabel5.setMaximumSize(new java.awt.Dimension(64, 84));
        mapLocationLabel5.setMinimumSize(new java.awt.Dimension(64, 84));
        mapLocationLabel5.setPreferredSize(new java.awt.Dimension(64, 84));
        mapLocationLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapLocationLabel5MouseClicked(evt);
            }
        });
        locationList = new ArrayList<MapLocationLabel>();
        locationList.add(mapLocationLabel1);
        locationList.add(mapLocationLabel2);
        locationList.add(mapLocationLabel3);
        locationList.add(mapLocationLabel4);
        locationList.add(mapLocationLabel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(mapLocationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mapLocationLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mapLocationLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(mapLocationLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(mapLocationLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(mapLocationLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(mapLocationLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mapLocationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mapLocationLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(mapLocationLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMousePressed
        frame.setContentPane(panel);
        frame.setVisible(true);
        
    }//GEN-LAST:event_backButtonMousePressed

    private void mapLocationLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapLocationLabel1MouseClicked
        if(level>= 1){
            GameView gw = new GameView(mapLocationLabel1.getLevelNumber(),"campaign",1,NationType.Doth);
            gw.copyFrameMain(frame);
            gw.copyContentPaneMain(panel);
            gw.Start();
            frame.setContentPane(gw);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_mapLocationLabel1MouseClicked

    private void mapLocationLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapLocationLabel2MouseClicked
        if(level>= 2){
            GameView gw = new GameView(mapLocationLabel2.getLevelNumber(),"campaign",1,NationType.Azad);
            gw.copyFrameMain(frame);
            gw.copyContentPaneMain(panel);
            gw.Start();
            frame.setContentPane(gw);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_mapLocationLabel2MouseClicked

    private void mapLocationLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapLocationLabel3MouseClicked
        if(level>= 3){
            GameView gw = new GameView(mapLocationLabel3.getLevelNumber(),"campaign",2,NationType.Cult);
            gw.copyFrameMain(frame);
            gw.copyContentPaneMain(panel);
            gw.Start();
            frame.setContentPane(gw);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_mapLocationLabel3MouseClicked

    private void mapLocationLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapLocationLabel4MouseClicked
        if(level>= 4){
            GameView gw = new GameView(mapLocationLabel4.getLevelNumber(),"campaign",2,NationType.Azad);
            gw.copyFrameMain(frame);
            gw.copyContentPaneMain(panel);
            gw.Start();
            frame.setContentPane(gw);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_mapLocationLabel4MouseClicked

    private void mapLocationLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapLocationLabel5MouseClicked
        if(level>= 5){
            GameView gw = new GameView(mapLocationLabel5.getLevelNumber(),"campaign",3,NationType.Doth);
            gw.copyFrameMain(frame);
            gw.copyContentPaneMain(panel);
            gw.Start();
            frame.setContentPane(gw);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_mapLocationLabel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private Controller.MapLocationLabel mapLocationLabel1;
    private Controller.MapLocationLabel mapLocationLabel2;
    private Controller.MapLocationLabel mapLocationLabel3;
    private Controller.MapLocationLabel mapLocationLabel4;
    private Controller.MapLocationLabel mapLocationLabel5;
    // End of variables declaration//GEN-END:variables
}
