/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JSlider;

/**
 *
 * @author KaanCakmak
 */
public class SoundSettingsWindow extends javax.swing.JPanel {

    /**
     * Creates new form SoundSettingsWindow
     */
    
    JFrame frame;
    Container panel;
    
    public SoundSettingsWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soundControl = new javax.swing.JSlider();
        muteButton = new javax.swing.JToggleButton();
        saveButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(200, 400));
        setMinimumSize(new java.awt.Dimension(200, 400));
        setPreferredSize(new java.awt.Dimension(200, 400));
        setLayout(null);

        soundControl.setMaximum(100);
        soundControl.setMinimum(0);
        soundControl.setMinorTickSpacing(1);
        soundControl.setValue(50);
        soundControl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                soundControlStateChanged(evt);
            }
        });
        add(soundControl);
        soundControl.setBounds(6, 82, 200, 26);

        muteButton.setText("Mute");
        muteButton.setToolTipText("");
        muteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muteButtonActionPerformed(evt);
            }
        });
        add(muteButton);
        muteButton.setBounds(121, 162, 61, 25);

        saveButton.setText("Save & Exit");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton);
        saveButton.setBounds(6, 6, 97, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void soundControlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_soundControlStateChanged
        soundControl = (JSlider)evt.getSource();
        float sound = (float)soundControl.getValue()/100;
        GraphicManager.sm.setVolume(sound);
    
    }//GEN-LAST:event_soundControlStateChanged

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        frame.setContentPane(panel);
        frame.setVisible(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void muteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muteButtonActionPerformed
        if(GraphicManager.sm.isPlaySong()){
            GraphicManager.sm.Pause();
        }
        else {
            GraphicManager.sm.Resume();
            muteButton.setText("Unmute");
        }
    }//GEN-LAST:event_muteButtonActionPerformed

    public void copyFrameMain(JFrame frame){
        this.frame = frame;
    }
    
    public void copyContentPaneMain(Container panel){
        this.panel = panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton muteButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JSlider soundControl;
    // End of variables declaration//GEN-END:variables
}
