/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author emre
 */
public class Tutorials extends javax.swing.JPanel {

    /**
     * Creates new form Tutorials
     */
    public Tutorials() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 1000));
        setMinimumSize(new java.awt.Dimension(400, 1000));
        setPreferredSize(new java.awt.Dimension(400, 1000));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyArsenal.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel2.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel2.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel1.setText("Enemy Arsenal");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyHospital.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel3.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel3.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel4.setText("Enemy Hospital");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyTailor.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        jLabel5.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel5.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel5.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel6.setText("Enemy Tailor");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playerArsenal.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        jLabel7.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel7.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel7.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel8.setText("Player Arsenal");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playerHospital.png"))); // NOI18N
        jLabel9.setText("jLabel2");
        jLabel9.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel9.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel9.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel10.setText("Player Hospital");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playerTailor.png"))); // NOI18N
        jLabel11.setText("jLabel2");
        jLabel11.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel11.setMinimumSize(new java.awt.Dimension(32, 32));
        jLabel11.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel12.setText("Player Tailor");

        jLabel13.setText("<html>Colony Wars is a time based strategy game that requires usage of a considerable</BR>"
            + "amount of strategical thinking. Game map basically consists of 2 main bases for each player</BR>"
            + "and several neutral bases that both players seeking to possess. The main purpose in the game</BR>"
            + "is to get control of all the bases in the game. Every base produces number of soldiers by time</BR>"
            + "passing. In order to get control of a base you need to have required amount of soldiers in it if</BR>"
            + "it is a neutral base, if it is an enemy base though you need to send more soldiers than enemy</BR>"
            + "soldiers that currently present in that base. There are several games similar to Colony Wars</BR>"
            + "currently on market to the writer’s knowledge that are popular one of them being Mushroom</BR>"
            + "Wars. The game also has variations of three nations each having advantage in one or more</BR>"
            + "of the soldier traits which are speed, production rate and soldier damage. First nation called</BR>"
            + "Cult has a greater speed and damage compared to other nations thanks to it greatly developed</BR>"
            + "weapons and clothing although the production rate of their species are low. Another nation in</BR>"
            + "the game is called Azad having faster production rates and movement speed compared to</BR>"
            + "others. They have smaller body sizes and are less developed which makes them fast and </BR>"
            + "increases their reproduction rates since less developed species produce more often. However</BR>"
            + "they have the drawback of having less damage than other species because of their small body</BR>"
            + "sizes. The last nation in the game is called Doth which is a male dominant colony with males</BR>"
            + "having more than one wife and are stronger compared to other species. However the nation is</BR>"
            + "considerably behind in sciences and technologies which come with the drawback to their</BR>"
            + "soldiers being slow compared to others.</BR>"
            + "The game will also have a campaign mode which includes a series of games all</BR>"
            + "having different objectives. Some examples for these varying objectives are as following:</BR>"
            + "- Capturing all bases.</BR>"
            + "- Capturing a particular base.</BR>"
            + "- Reaching a particular amount of soldiers.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
